  #'  Data Integration RSF Model
  #'  SEFS 521
  #'  November 2020
  #'  --------------------------------------------
  #'  Combines observations of cougar and elk, respectively, in the WPPP Northeast 
  #'  study area from Dec 1, 2018 - Mar 31, 2019. Observations collected from 55  
  #'  camera traps, 44 elk GPS collars & 24 cougar GPS collars under one habitat 
  #'  selection model.
  #'  
  #'  Model written by Dr. Beth Gardner
  #'  --------------------------------------------

  #'  Clean out the environment
  rm(list = ls())

  #'  Load libraries
  #library(rjags)
  library(R2jags)
  load.module("glm")
  library(mcmcplots)
  library(tidyverse)
  
  #'  Read in data and format for model
  #'  Species specific telemetry data
  elk <- read.csv("./Elk_4hrFix_Cell_Count_withNAs 2020-11-25.csv") %>%
    select(-X)
  coug <- read.csv("./Cougar_4hrFix_Cell_Count 2020-11-28.csv")
  #'  Camera trap detection data
  cams <- read.csv("./Camera_detections.csv") %>%
    select(-X)
  #'  Covariate data
  cov <- read.csv("./Covariates_by_cell.csv")
  
  #'  Covariate data
  cov <- cov %>%
    select(-grid_cell_NE) %>%
    #'  Center and scale covariate data
    mutate(
      zDEM = scale(DEM_val, center = TRUE, scale = TRUE),
      zRoads = scale(roads_val, center = TRUE, scale = TRUE)
    )
  #'  Add MCP boundary to covariate data
  covs <- cbind(cov, elk$MCP, coug$MCP) %>%
    relocate(zDEM, .after = DEM_val) %>%
    relocate(zRoads, .after = roads_val)
  #'  Camera sampling effort not included b/c not many cameras fall outside the
  #'  total_MCP generated by the elk & cougar locations -> mismatched dimensions

  #'  Rename columns for easier use in model  
  colnames(covs) <- c("DEM", "zDEM", "Roads", "zRoads", "NLCD", "NLCD_names", 
                      "Elk_MCP", "Coug_MCP") 
  #'  Create dummy variables for NLCD covariate
  unique(covs$NLCD_names)
  nlcd <- as.factor(covs$NLCD_names)
  habitat <- as.data.frame(cbind(as.character(nlcd), as.character(nlcd), as.character(nlcd), 
                              as.character(nlcd), as.character(nlcd), as.character(nlcd), 
                              as.character(nlcd))) %>%
    transmute(
      forest = ifelse(V1 == "forest", 1, 0),
      shrub = ifelse(V2 == "shrubland", 1, 0),
      crops = ifelse(V3 == "fields_crops", 1, 0),
      water = ifelse(V4 == "water", 1, 0),
      grass = ifelse(V5 == "grassland", 1, 0),
      other = ifelse(V6 == "wetlands" | V6 == "lowdevelop", 1, 0)
    )
  
  covs <- cbind(covs, habitat)
  
  #'  Covariate data for only grid cells with cameras
  cam_and_covs <- cbind(cams, covs)
  elk_covs <- cam_and_covs[!is.na(cam_and_covs$Elk_Detections),] %>%
    select(-c(cell, Camera_Sampled, Cougar_Detections, Elk_Detections))
  coug_covs <- cam_and_covs[!is.na(cam_and_covs$Cougar_Detections),] %>%
    select(-c(cell, Camera_Sampled, Cougar_Detections, Elk_Detections))
  
  #'  Focus only on grid cells within MCPs
  #'  Tons of 0's from cells outside MCP (and thus no collar data) otherwise
  all <- full_join(elk, coug, by = "cell") %>%
    mutate(
      total_MCP = ifelse(MCP.x == 1 | MCP.y == 1, 1, 0)
    )
  mcp_elk <- elk[all$total_MCP == 1,]
  mcp_coug <- coug[all$total_MCP == 1,]
  mcp_cov <- covs[all$total_MCP == 1,]
  mcp_cams <- cams[all$total_MCP == 1,]
  #'  Do we lose any cameras by focusing on only cells within the total MCP?
  #'  Should have 55 cameras if none are lost
  colSums(mcp_cams, na.rm = TRUE)

  #'  Species-specific camera detection data
  #'  Remove un-sampled grid cells
  #'  Change to vector instead of data frame
  elk_cams <- select(mcp_cams, Elk_Detections) %>%  
    #'  Using mcp_cams not needed but staying consistent with workflow
    filter(!is.na(.))
  elk_cams <- elk_cams[["Elk_Detections"]]
  coug_cams <- select(mcp_cams, Cougar_Detections) %>%
    filter(!is.na(.))
  coug_cams <- coug_cams[["Cougar_Detections"]]
  
  #'  Telemetry observation data only
  elk_telem <- as.matrix(select(mcp_elk, -c(cell, MCP)))  # elk if including ALL grid cells
  elk_telem <- t(elk_telem) # transposing matrix so rows = animal, column = grid cell
  coug_telem <- as.matrix(select(mcp_coug, -c(cell, MCP)))  # coug if including ALL grid cells
  coug_telem <- t(coug_telem) # transposing matrix so rows = animal, column = grid cell

  #'  Look over the data & create a few summary statistics
  #'  Keep in mind telemetry data are arranged as individual grid cells (rows) by
  #'  number of individual locations per grid cell (columns)
  dim(elk_telem)
  dim(elk_cams) # vector so dim should be NULL
  dim(coug_telem)
  dim(coug_cams) # vector so dim should be NULL
  dim(mcp_cov) # covs if including ALL grid cells
  
  head(elk_telem[,1:6])
  head(coug_telem[,1:6])
  head(elk_cams)
  head(coug_cams)
  
  #'  Sum total number of telemetry locations per individual animal
  #sumelk <- colSums(elk_telem)
  #sumcoug <- colSums(coug_telem)
  sumelk <- rowSums(elk_telem)  # if matrix is transposed
  sumcoug <- rowSums(coug_telem)  # if matrix is transposed
  
  #'  Number of grid cells, cameras, and telemetered animals
  #'  Keep in mind multiple cameras fall within one grid cell so think about 
  #'  whether this should be number of cameras total (55) or number of grids with
  #'  cameras in them (<55)
  ngrid <- nrow(mcp_cov) # covs if including ALL grid cells
  #ncam <- sum(cams$Camera_Sampled, na.rm = TRUE) # Number of cameras total
  ncam <- sum(!is.na(cams$Camera_Sampled)) # Number of cells with cameras
  # nelk <- length(elk_telem)
  # ncoug <- length(coug_telem)
  nelk <- nrow(elk_telem)  # if matrix is transposed
  ncoug <- nrow(coug_telem)  # if matrix is transposed

  #'  ---------------------------------------------------
  #'  Helpful definitions for input data and estimated/derived parameters
  #'  DATA
  #'  ngrid = number of grid cells
  #'  ncam = number of camera traps
  #'  n = number of telemetered animals
  #'  R = total number of telemetry locations for an individual animal
  #'  M = number of telemetry locations per individual per grid cell
  #'  y = total number of species-specific detections in a grid cell
  #'  
  #'  PATAMETERS
  #'  a_telem = random effect for each telemetered animal
  #'  pi = a categorical probability that each grid cell is used by an individual
  #'       animal; calculated by dividing the site-specific estimates of lambda
  #'       for a given individual by the mean lambda for that individual 
  #'       (averaged across all sites)
  #'  lam_telem = (lambda) the intensity or rate parameter representing the estimated  
  #'        mean number of telemetry locations in a grid cell for an individual 
  #'        animal during the study period
  #'  a_cam = random effect for each camera site
  #'  lam_cam = (lambda) the intensity or rate parameter representing the estimated
  #'         mean number of independent detection events of a given species at
  #'         a camera site during the study period
  #'  b1 = beta coefficient for the effect of a given covariate on the number of 
  #'       animal observations; NOTE: estimating the same b1 for both types 
  #'       of data to connect the two observation processes under one model
  #'  ---------------------------------------------------

  #'  Combined model for both gps and camera data
  cat("
  model{
  
    #'  Telemetry half of the model
    for(i in 1:n){
    
      #'  Random intercept for each individual
      a_telem[i] ~ dnorm(int_telem, tau_telem)
      
      #'  The number of observed telemetry locations in a grid cell arises from a 
      #'  categorical distribution based on the probability that a given cell is  
      #'  used by that individual and the total number of its telemetry locations
      M[i,1:ngrid] ~ dmulti(pi[i,1:ngrid], R[i])
    
    
      for(j in 1:ngrid){
      
        #'  Estimate the site- and individual-specific values of lambda
        # log(lam_telem[i,j]) = a_telem[i] + b1*X_telem[j]
        # log(lam_telem[i,j]) = a_telem[i] + b_elev*telev[j]
        # log(lam_telem[i,j]) = a_telem[i] + b_road*troad[j]
        log(lam_telem[i,j]) = a_telem[i] + b_elev*telev[j] + b_road*troad[j]
        #'  Forest is reference variable for NLCD categorical covariate
        # log(lam_telem[i,j]) = a_telem[i] + b_shrub*tshrub[j] + b_crop*tcrop[j] +
        #   b_water*twater[j] + b_grass*tgrass[j] + b_other*tother[j]
        
        #'  Calculating pi based on lambda estimates
        pi[i,j] = lam_telem[i,j]/sum(lam_telem[i,1:ngrid])  # remove the correction of dividing by sum of lam?
      
      }
    }
    
    #'  Camera trap half of the model
    for(k in 1:ncam){
      
      #'  Random effect for each camera
      a_cam[k] ~ dnorm(int_cam, tau_cam)
      
      #'  The number of observed detections at a camera site arises from a 
      #'  Poisson distribution based on the intensity or mean number of independent
      #'  detection events for a given species during the study period 
      y[k] ~ dpois(lam_cam[k])
      
      #'  Estimate the camera-site specific values of lambda 
      # log(lam_cam[k]) <- a_cam[k] + b1*X_cam[k]
      # log(lam_cam[k]) <- a_cam[k] + b_elev*celev[k]
      # log(lam_cam[k]) <- a_cam[k] + b_road*croad[k]
      log(lam_cam[k]) <- a_cam[k] + b_elev*celev[k] + b_road*croad[k]
      #'  Forest is reference variable for NLCD categorical covariate
      # log(lam_cam[k]) <- a_cam[k] + b_shrub*cshrub[k] + b_crop*ccrop[k]
    }
    
    
    #'  Priors
    int_telem ~ dnorm(0, 0.1)
    tau_telem ~ dunif(0, 10)
    # b1 ~ dnorm(0, 0.1)
    b_elev ~ dnorm(0, 0.1)
    b_road ~ dnorm(0, 0.1)
    # b_shrub ~ dnorm(0, 0.1)
    # b_crop ~ dnorm(0, 0.1)
    # b_water ~ dnorm(0, 0.1)
    # b_grass ~ dnorm(0, 0.1)
    # b_other ~ dnorm(0, 0.1)
    
    
    int_cam ~ dnorm(0, 0.1)
    tau_cam ~ dunif(0, 4)
    
    
    #'  Derived parameters

    #'  Averaged across telemetered animals
    #'  Expected number of total locations per grid cell
    for(j in 1:ngrid) {
      mu_lam[j] <- mean(lam_telem[,j])
    }
    
  }
  
  ", fill = TRUE, file = "combo.txt")
  
  
  
  #'  Arguments for jags
  #'  Elk data   
  # data <- list(M = elk_telem, R = sumelk, telev = as.vector(mcp_cov$zDEM),
  #              celev = as.vector(elk_covs$zDEM), ngrid = ngrid, n = nelk,
  #              ncam = ncam, y = elk_cams)
  # data <- list(M = elk_telem, R = sumelk, troad = as.vector(mcp_cov$zRoads),
  #              croad = as.vector(elk_covs$zRoads), ngrid = ngrid, n = nelk,
  #              ncam = ncam, y = elk_cams)
  data <- list(M = elk_telem, R = sumelk, telev = as.vector(mcp_cov$zDEM),
               troad = as.vector(mcp_cov$zRoads), celev = as.vector(elk_covs$zDEM),
               croad = as.vector(elk_covs$zRoads), ngrid = ngrid, n = nelk,
               ncam = ncam, y = elk_cams)
  # data <- list(M = elk_telem, R = sumelk, ngrid = ngrid, n = nelk, ncam = ncam, y = elk_cams,
  #              tshrub = as.vector(mcp_cov$shrub), tcrop = as.vector(mcp_cov$crops), 
  #              twater = as.vector(mcp_cov$water), tgrass = as.vector(mcp_cov$grass), 
  #              tother = as.vector(mcp_cov$other), cshrub = as.vector(elk_covs$shrub),
  #              ccrop = as.vector(elk_covs$crops))
  
  #'  Cougar data
  # data <- list(list(M = coug_telem, R = sumcoug, X = as.vector(mcp_cov$zDEM), 
  #                   Xc = as.vector(coug_covs$zDEM), ngrid = ngrid, n = nelk, 
  #                   ncam = ncam, y = coug_cams))
  
  # parameters = c('a_telem', 'a_cam', 'b1', 'int_telem', 'tau_telem', 'int_cam', 
  #                'tau_cam', 'mu_lam', 'lam_cam')
  # parameters = c('a_telem', 'a_cam', 'int_telem', 'tau_telem', 'int_cam', 'tau_cam', 
  #               'mu_lam', 'lam_cam', 'b_elev')
  # parameters = c('a_telem', 'a_cam', 'int_telem', 'tau_telem', 'int_cam', 'tau_cam', 
  #                'mu_lam', 'lam_cam', 'b_road')
  parameters = c('a_telem', 'a_cam', 'int_telem', 'tau_telem', 'int_cam', 'tau_cam',
                 'mu_lam', 'lam_cam', 'b_elev', 'b_road')
  # parameters = c('a_telem', 'a_cam', 'int_telem', 'tau_telem', 'int_cam', 'tau_cam', 
  #                'mu_lam', 'lam_cam', 'b_shrub', 'b_crop', 'b_water', 'b_grass', 'b_other')
  
  
  #inits = function() {list(b1 = rnorm(1))}
  # inits = function() {list(b_elev = rnorm(1))}
  # inits = function() {list(b_road = rnorm(1))}
  inits = function() {list(b_elev = rnorm(1), b_road = rnorm(1))}
  # inits = function() {list(b_shrub = rnorm(1), b_crop = rnorm(1), b_water = rnorm(1), 
  #                          b_grass = rnorm(1), b_other = rnorm(1))}
  
  
  #'  Call to jags
  out <- jags(data, inits, parameters, "combo.txt", 
              n.chains = 3, n.thin = 1, n.iter = 2000, n.burnin = 1000)
  print(out, dig = 3)
  mcmcplot(out)

  
  #'  Hold on to model output
  combo_elev_rd_output <- out
  save(combo_elev_rd_output, file = "./Output/combo_elev_rd_output.RData")
  
  #'  Put everything on the probability scale to estimate Probability of Use, which
  #'  represents the probability that a cell is used by an individual (telemetry)
  #'  and the probability that a camera site is used in a grid cell (camera)
  #'  during the study period.

  #'  Extract all iterations of telemetry- and camera-based lambdas
  mu_lam <- combo_elev_rd_output$BUGSoutput$sims.list$mu_lam
  lam_cam <- combo_elev_rd_output$BUGSoutput$sims.list$lam_cam
  
  #'  Loop through each iteration for each grid cell and calculate probability
  #'  Telemetry results
  tel_prob <- matrix(nrow = nrow(mu_lam), ncol = ngrid)
  for(i in 1:nrow(mu_lam)){
    for(j in 1:ngrid){
      tel_prob[i,j] <- 1-exp(-(mu_lam[i,j]))
    }
  }
  #'  Camera results
  det_prob <- matrix(nrow = nrow(lam_cam), ncol = ncam)
  for(i in 1:nrow(lam_cam)){
    for(k in 1:ncam){
      det_prob[i,k] <- 1-exp(-(lam_cam[i,k]))
    }
  }
  #'  Transpose so rows = grid cells & save as a data frame
  tel_prob <- as.data.frame(t(tel_prob))
  det_prob <- as.data.frame(t(det_prob))
  
  #' Save estimated probability of use based on each data source
  #' Pair probability of use with the original grid cell number it was estimated for
  cell <- mcp_elk$cell
  pr_use_elev_rd_tel <- cbind(cell, tel_prob)
  cell <- cam_and_covs$cell[!is.na(cam_and_covs$Elk_Detections)]
  pr_use_elev_rd_cam <- cbind(cell, det_prob)
  
  save(pr_use_elev_rd_tel, file = "./Output/pr_use_elev_rd_tel.RData")
  save(pr_use_elev_rd_cam, file = "./Output/pr_use_elev_rd_cam.RData")
  
  #################################
  
  #'  RSF with telemetry data only
  cat("
  model{
    
    for(i in 1:n){
    
      a_telem[i] ~ dnorm(int_telem, tau_telem)
      M[i,1:ngrid] ~ dmulti(pi[i,1:ngrid], R[i])
      
      for(j in 1:ngrid){
      
        #log(lam_telem[i,j]) = a_telem[i] + b1*X_telem[j]
        # log(lam_telem[i,j]) = a_telem[i] + b_elev*telev[j]
        # log(lam_telem[i,j]) = a_telem[i] + b_road*troad[j]
        log(lam_telem[i,j]) = a_telem[i] + b_elev*telev[j] + b_road*troad[j]
        # log(lam_telem[i,j]) = a_telem[i] + b_shrub*tshrub[j] + b_crop*tcrop[j] +
        #   b_water*twater[j] + b_grass*tgrass[j] + b_other*tother[j]        
        pi[i,j] = lam_telem[i,j]/sum(lam_telem[i,1:ngrid])

      
      }
    }
    
    #'  Priors
    int_telem ~ dnorm(0, 0.1)
    tau_telem ~ dunif(0, 10)
    # b1 ~ dnorm(0, 0.1)
    b_elev ~ dnorm(0, 0.1)
    b_road ~ dnorm(0, 0.1)
    # b_shrub ~ dnorm(0, 0.1)
    # b_crop ~ dnorm(0, 0.1)
    # b_water ~ dnorm(0, 0.1)
    # b_grass ~ dnorm(0, 0.1)
    # b_other ~ dnorm(0, 0.1)
    
    #'  Derived parameters
    #'  Averaged across telemetered animals
    #'  Expected number of total locations per grid cell
    for(j in 1:ngrid) {
      mu_lam[j] <- mean(lam_telem[,j])
    }
  
  }
  
  ", fill = TRUE, file = "telem.txt")
  
  
  #'  Arguments for jags
  data <- list(M = elk_telem, R = sumelk, telev = as.vector(mcp_cov$zDEM),
               troad = as.vector(mcp_cov$zRoads), ngrid = ngrid, n = nelk)
  # data <- list(M = elk_telem, R = sumelk, ngrid = ngrid, n = nelk,  
  #              tshrub = as.vector(mcp_cov$shrub), tcrop = as.vector(mcp_cov$crops), 
  #              twater = as.vector(mcp_cov$water), tgrass = as.vector(mcp_cov$grass), 
  #              tother = as.vector(mcp_cov$other))
  # data <- list(M = coug_telem, R = sumcoug, X = as.vector(mcp_cov$zDEM), ngrid = ngrid, 
  #              n = ncoug)
  parameters = c('a_telem', 'int_telem', 'tau_telem', 'mu_lam', 'b_elev', 'b_road')
  # parameters = c('a_telem','int_telem','tau_telem', 'mu_lam',
  #                'b_shrub', 'b_crop', 'b_water', 'b_grass', 'b_other') #'b1', 
  
  #inits = function() {list(b1=rnorm(1))}  
  # inits = function() {list(b_elev = rnorm(1))}
  # inits = function() {list(b_road = rnorm(1))}
  inits = function() {list(b_elev = rnorm(1), b_road = rnorm(1))}
  # inits = function() {list(b_shrub = rnorm(1), b_crop = rnorm(1), b_water = rnorm(1), 
  #                          b_grass = rnorm(1), b_other = rnorm(1))}
  
  
  # call to jags
  out <- jags(data, inits, parameters, "telem.txt", 
              n.chains = 3, n.thin = 1, n.iter = 2000, n.burnin = 1000)
  print(out, dig = 3)
  mcmcplot(out)

  #'  Hold on to model output
  telem_elev_rd_output <- out
  save(telem_elev_rd_output, file = "./Output/telem_elev_rd_output.RData")
  
  #'  Put everything on the probability scale to estimate Probability of Use
  #'  Represents the probability of 1 or more telemetry locations/camera
  #'  detections occurring in a given grid cell during the study period.
  # mu_lam <- telem_dem_output$BUGSoutput$mean$mu_lam
  # lamc <- telem_dem_output$BUGSoutput$mean$lamc
  # 
  # tel_prob <- c()
  # 
  # for(j in 1:ngrid){
  #   tel_prob[j] <- 1-exp(-(mu_lam[j]))
  # }

  
  ############################################
  
  #'  Camera data only
  cat("
    model{
    
    for(k in 1:ncam){
      a_cam[k] ~ dnorm(int_cam, tau_cam)
      y[k] ~ dpois(lam_cam[k])
      #log(lam_cam[k]) <- a_cam[k] + b1*X_cam[k]
      # log(lam_cam[k]) <- a_cam[k] + b_elev*celev[k]
      # log(lam_cam[k]) <- a_cam[k] + b_road*croad[k]
      log(lam_cam[k]) <- a_cam[k] + b_elev*celev[k] + b_road*croad[k]
      # log(lam_cam[k]) <-  a_cam[k] + b_shrub*cshrub[k] + b_crop*ccrop[k]  

    }
    
    #'  Priors
    # b1 ~ dnorm(0, 0.1)
    b_elev ~ dnorm(0, 0.1)
    b_road ~ dnorm(0, 0.1)
    # b_shrub ~ dnorm(0, 0.1)
    # b_crop ~ dnorm(0, 0.1)
    int_cam ~ dnorm(0, 0.1)
    tau_cam ~ dunif(0, 4)
    
  }
  
  ", fill = TRUE, file = "cam.txt")
  
  
  
  #'  Arguments for jags
  #data = list(X_cam = as.vector(elk_covs$zDEM), ncam = ncam, y = elk_cams)
  # data = list(y = elk_cams, ncam = ncam, cshrub = as.vector(elk_covs$shrub),
  #             ccrop = as.vector(elk_covs$crops))
  data <- list(ncam = ncam, y = elk_cams, ngrid = ngrid, n = nelk,
               celev = as.vector(elk_covs$zDEM), croad = as.vector(elk_covs$zRoads))
  # data = list(X_cam = as.vector(coug_covs$zDEM), ncam = ncam, y = coug_cams)
  # parameters = c('a_cam', 'int_cam', 'tau_cam', 'lam_cam', 'b_shrub', 'b_crop')
  parameters = c('a_cam', 'int_cam', 'tau_cam', 'lam_cam', 'b_elev', 'b_road') # 'b1',
  
  
  #inits = function() {list(b1=rnorm(1))}
  inits = function() {list(b_elev = rnorm(1), b_road = rnorm(1))}
  # inits = function() {list(b_shrub = rnorm(1), b_crop = rnorm(1))}
  
  
  # call to jags
  out <- jags(data, inits, parameters, "cam.txt", 
              n.chains = 3, n.thin = 1, n.iter = 2000, n.burnin = 1000)
  print(out, dig = 2)
  mcmcplot(out)

  #'  Hold on to model output
  cam_elev_rd_output <- out
  save(cam_elev_rd_output, file = "./Output/cam_elev_rd_output.RData")
  
  
  #'  Put everything on the probability scale to estimate Probability of Use
  #'  Represents the probability of 1 or more telemetry locations/camera
  #'  detections occurring in a given grid cell during the study period.
  # mu_lam <- cam_dem_output$BUGSoutput$mean$mu_lam
  # lamc <- cam_dem_output$BUGSoutput$mean$lamc
  # 
  # det_prob <- c()
  # 
  # for(k in 1:ncam) {
  #   det_prob[k] <- 1-exp(-(lam_cam[k]))
  # }
  