  #'  Input data wrangling for integrated model
  #'  SEFS 521
  #'  December 2020
  #'  ------------------------------------------------------
  #'  Wrangle telemetry and camera trap data for an integrated data analysis. 
  #'  Save output so it all can be read into Data_Integration_RSF_Model.R
  #'  ------------------------------------------------------
  
  #'  Clean out the environment
  rm(list = ls())
  
  #'  Load libraries
  library(tidyverse)
  
  #'  Read in data and format for model
  #'  Species specific telemetry data
  elk <- read.csv("./Elk_4hrFix_Cell_Count_withNAs 2020-11-25.csv") %>%
    dplyr::select(-X)
  coug <- read.csv("./Cougar_4hrFix_Cell_Count 2020-11-28.csv")
  #'  Camera trap detection data
  cams <- read.csv("./Camera_detections.csv") %>%
    dplyr::select(-X)
  #'  Covariate data
  cov <- read.csv("./Covariates_by_cell.csv")
  
  #'  Covariate data
  cov <- cov %>%
    dplyr::select(-grid_cell_NE) %>%
    #'  Center and scale covariate data
    mutate(
      zDEM = scale(DEM_val, center = TRUE, scale = TRUE),
      zRoads = scale(roads_val, center = TRUE, scale = TRUE),
      landcov = as.numeric(as.factor(NLCD_label))
    )
  #'  Add MCP boundary to covariate data
  covs <- cbind(cov, elk$MCP, coug$MCP) %>%
    relocate(zDEM, .after = DEM_val) %>%
    relocate(zRoads, .after = roads_val) 
  #'  Camera sampling effort not included b/c not many cameras fall outside the
  #'  total_MCP generated by the elk & cougar locations -> mismatched dimensions
  
  #'  Rename columns for easier use in model  
  colnames(covs) <- c("DEM", "zDEM", "Roads", "zRoads", "NLCD", "NLCD_names", 
                      "landcov", "Elk_MCP", "Coug_MCP") 
  #'  Create dummy variables for NLCD covariate
  # unique(covs$NLCD_names)
  # nlcd <- as.factor(covs$NLCD_names)
  # habitat <- as.data.frame(cbind(as.character(nlcd), as.character(nlcd), as.character(nlcd), 
  #                                as.character(nlcd), as.character(nlcd), as.character(nlcd), 
  #                                as.character(nlcd))) %>%
  #   transmute(
  #     forest = ifelse(V1 == "forest", 1, 0),
  #     shrub = ifelse(V2 == "shrubland", 1, 0),
  #     crops = ifelse(V3 == "fields_crops", 1, 0),
  #     water = ifelse(V4 == "water", 1, 0),
  #     grass = ifelse(V5 == "grassland", 1, 0),
  #     other = ifelse(V6 == "wetlands" | V6 == "lowdevelop", 1, 0)
  #   )
  # 
  # covs <- cbind(covs, habitat)
  
  #'  Covariate data for only grid cells with cameras
  cam_and_covs <- cbind(cams, covs)
  elk_covs <- cam_and_covs[!is.na(cam_and_covs$Elk_Detections),] %>%
    dplyr::select(-c(cell, Camera_Sampled, Cougar_Detections, Elk_Detections))
  coug_covs <- cam_and_covs[!is.na(cam_and_covs$Cougar_Detections),] %>%
    dplyr::select(-c(cell, Camera_Sampled, Cougar_Detections, Elk_Detections))
  
  #'  Focus only on grid cells within MCPs
  #'  Tons of 0's from cells outside MCP (and thus no collar data) otherwise
  all <- full_join(elk, coug, by = "cell") %>%
    mutate(
      total_MCP = ifelse(MCP.x == 1 | MCP.y == 1, 1, 0)
    )
  mcp_elk <- elk[all$total_MCP == 1,]
  mcp_coug <- coug[all$total_MCP == 1,]
  mcp_cov <- covs[all$total_MCP == 1,]
  mcp_cams <- cams[all$total_MCP == 1,]
  #'  Do we lose any cameras by focusing on only cells within the total MCP?
  #'  Should have 55 cameras if none are lost
  colSums(mcp_cams, na.rm = TRUE)
  
  #'  Species-specific camera detection data
  #'  Remove un-sampled grid cells
  #'  Change to vector instead of data frame
  #'  Using mcp_cams not needed but staying consistent with work flow
  #'  Number of unique detection events per species per grid cell
  # elk_cams <- dplyr::select(mcp_cams, Elk_Detections) %>%
  #   filter(!is.na(.))
  # elk_cams <- elk_cams[["Elk_Detections"]]
  # coug_cams <- dplyr::select(mcp_cams, Cougar_Detections) %>%
  #   filter(!is.na(.))
  # coug_cams <- coug_cams[["Cougar_Detections"]]
  
  #'  Species-specific counts from ind. detection events per grid cell
  elk_cams <- dplyr::select(mcp_cams, Elk_Counts) %>%  
    filter(!is.na(.))
  elk_cams <- elk_cams[["Elk_Counts"]]
  coug_cams <- dplyr::select(mcp_cams, Cougar_Counts) %>%
    filter(!is.na(.))
  coug_cams <- coug_cams[["Cougar_Counts"]]
  
  #'  Telemetry observation data only
  elk_telem <- as.matrix(dplyr::select(mcp_elk, -c(cell, MCP)))  # elk if including ALL grid cells
  elk_telem <- t(elk_telem) # transposing matrix so rows = animal, column = grid cell
  coug_telem <- as.matrix(dplyr::select(mcp_coug, -c(cell, MCP)))  # coug if including ALL grid cells
  coug_telem <- t(coug_telem) # transposing matrix so rows = animal, column = grid cell
  
  #'  Look over the data & create a few summary statistics
  #'  Keep in mind telemetry data are arranged as individual grid cells (rows) by
  #'  number of individual locations per grid cell (columns)
  dim(elk_telem)
  dim(elk_cams) # vector so dim should be NULL
  dim(coug_telem)
  dim(coug_cams) # vector so dim should be NULL
  dim(mcp_cov) # covs if including ALL grid cells
  
  head(elk_telem[,1:6])
  head(coug_telem[,1:6])
  head(elk_cams)
  head(coug_cams)
  
  #'  Sum total number of telemetry locations per individual animal
  #sumelk <- colSums(elk_telem)
  #sumcoug <- colSums(coug_telem)
  sumelk <- rowSums(elk_telem)  # if matrix is transposed
  sumcoug <- rowSums(coug_telem)  # if matrix is transposed
  
  #'  Number of grid cells, cameras, and telemetered animals
  #'  Keep in mind multiple cameras fall within one grid cell so think about 
  #'  whether this should be number of cameras total (55) or number of grids with
  #'  cameras in them (<55)
  ngrid <- nrow(mcp_cov) # covs if including ALL grid cells
  #ncam <- sum(cams$Camera_Sampled, na.rm = TRUE) # Number of cameras total
  ncam <- sum(!is.na(cams$Camera_Sampled)) # Number of cells with cameras
  # nelk <- length(elk_telem)
  # ncoug <- length(coug_telem)
  nelk <- nrow(elk_telem)  # if matrix is transposed
  ncoug <- nrow(coug_telem)  # if matrix is transposed
